# 背离策略

In [194]:
import json
import os
from datetime import datetime, timedelta
from dataclasses import dataclass
from typing import Optional
import math
import time
from collections import deque
from decimal import Decimal


import numpy as np
import pandas as pd
import talib as ta
import mplfinance as mpf
from dotenv import load_dotenv
from okx.MarketData import MarketAPI
from pandas import DataFrame
from tqdm import tqdm

from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = 'all'

load_dotenv()
KEY = os.getenv("OKX_API_KEY")
SECRET = os.getenv("OKX_API_SECRET")
assert KEY and SECRET, "API key and secret are required"
market = MarketAPI(KEY, SECRET, flag="0", debug=False)

def to_candles(data: list) -> DataFrame:
    """将数据转换为用于绘制 K 线图的 DataFrame

    Args:
        data: JSON 数据

    Returns:
        DataFrame: 一组 K 线数据帧
    """
    df = pd.DataFrame(
        data,
        columns=[
            "ts",
            "open",
            "high",
            "low",
            "close",
            "volume",
            "volCcy",
            "volCcyQuote",
            "_",
        ],
    )
    return df

def get_current_candlestick(instId: str, bar: str = "1H") -> DataFrame:
    """获取当前 K 线数据"""
    if not isinstance(instId, str):
        raise TypeError("instId must be a string")

    # 获取最近 3 个小时级别的 K 线数据
    resp = market.get_candlesticks(instId, bar=bar, limit="2")
    data = resp["data"]
    df = to_candles(data)
    return df


def get_period(bar):
    """
    根据给定的时间条形（bar）字符串，返回相应的时间周期（以毫秒为单位）。

    参数:
    bar (str): 时间条形字符串，例如 "1s", "1m", "3m", "5m", "15m", "1H", "2H", "4H", "1D"

    返回:
    int: 对应的时间周期，以毫秒为单位

    异常:
    ValueError: 如果输入的 bar 值不在预定义的范围内
    """
    if bar == "1s":
        period = 1 * 1000
    elif bar == "1m":
        period = 60 * 1000
    elif bar == "3m":
        period = 180 * 1000
    elif bar == "5m":
        period = 300 * 1000
    elif bar == "15m":
        period = 900 * 1000
    elif bar == "1H":
        period = 3600 * 1000
    elif bar == "2H":
        period = 7200 * 1000
    elif bar == "4H":
        period = 14400 * 1000
    elif bar == "1D":
        period = 86400 * 1000
    else:
        period = 0
    return period


def get_candlesticks(instId: str, after: int | None = None, before: int | None = None, bar: str = "1H") -> pd.DataFrame:
    """获取 K 线数据, 包含历史数据和最新数据"""
    if not isinstance(instId, str):
        raise TypeError("instId must be a string")

    dst_dir = f"./data/{instId}/{bar}"
    file_path = f"./data/{instId}/{bar}/{instId}.json"
    period = get_period(bar)
    
    # 获取最新的 K 线数据
    latest_df = get_current_candlestick(instId, bar)
    history_data = []
    after_list = [int(after)]
    now_timestamp = datetime.now().timestamp() * 1000
    while 1:
        # print(after_list[-1], period)
        _after = after_list[-1] + period * 100
        after_list.append(_after)
        if _after > now_timestamp:
            break
            
    # 获取历史的 K 线数据
    for _after in tqdm(after_list):
        resp = market.get_history_candlesticks(instId, bar=bar, after=str(_after))
        data = resp["data"]
        # print(data)
        history_data.extend(data)
        if len(data) == 0:
            break
        time.sleep(0.1)
    
    history_df = to_candles(history_data)
    df = merge_candlesticks(history_df, latest_df)
    data = df.to_dict(orient="records")
    os.makedirs(dst_dir, exist_ok=True)
    with open(file_path, "w") as f:
        f.write(json.dumps(data, indent=4))
    return df

def merge_candlesticks(df1: DataFrame, df2: DataFrame) -> DataFrame:
    """合并两个 K 线数据帧

    Args:
        df1: K 线数据帧 1
        df2: K 线数据帧 2

    Returns:
        DataFrame: 合并后的 K 线数据帧
    """
    # 合并历史数据和最新数据，按时间戳去重，保留 '_' 为 1 的数据，即收盘数据
    df = pd.concat([df1, df2], ignore_index=True)
    df.drop_duplicates("ts", keep="last", inplace=True)
    df.sort_values("ts", ascending=True, inplace=True)
    return df

True

In [195]:
# 获取过去一天的数据
def get_df(instId, bar):
    start = datetime.now() - timedelta(days=10)
    df = get_candlesticks(instId, bar=bar, after=start.timestamp() * 1000)
    df.reset_index(drop=True, inplace=True)
    df["ts"] = df["ts"].astype(int)
    df["ts"] = pd.to_datetime(df["ts"], unit="ms") + timedelta(hours=8)
    df["high"] = df["high"].apply(lambda x: Decimal(x))
    df["low"] = df["low"].apply(lambda x: Decimal(x))
    df["close"] = df["close"].apply(lambda x: Decimal(x))
    df["hlc3"] = (df["high"] + df["low"] + df["close"]) / 3

    fastMfi = ta.MFI(df['high'], df['low'], df['close'], df['volume'], timeperiod=fastMfiLen)
    slowMfi = ta.MFI(df['high'], df['low'], df['close'], df['volume'], timeperiod=slowMfiLen)
    resMfi = transform(ta.SMA((fastMfi * 0.5 + slowMfi * 0.5), timeperiod=smoothHist), 0.7)

    mfi = ta.MFI(df['high'], df['low'], df['close'], df['volume'], timeperiod=MFI_LEN)
    rsi = ta.RSI(df['hlc3'], timeperiod=rsiLen)
    # 计算Stochastic RSI
    stoch_rsi_k, stoch_rsi_d = ta.STOCH(rsi, rsi, rsi, fastk_period=rsiLen, slowk_period=1, slowk_matype=0, slowd_period=1, slowd_matype=0)
    # 计算STOCH_K的SMA
    stoch = ta.SMA(stoch_rsi_k, timeperiod=STOCH_K)
    sigStoch = ta.SMA(stoch, timeperiod=STOCH_D)
    df["mfi"] = mfi
    df["rsi"] = rsi
    df["stoch"] = stoch
    df["sigStoch"] = sigStoch
    
    signal = (rsi + mfiWeight * mfi + STOCH_WEIGHT * stoch) / (1 + mfiWeight + STOCH_WEIGHT)
    avg = transform(ta.EMA(signal, smoothLen), EXTEND_MULT)
    avg2 = transform(ta.EMA(signal, round(smoothLen * SMOOTH_LEN)), EXTEND_MULT)

    df['resMfi'] = resMfi
    df['signal'] = signal
    df['avg'] = avg
    df['avg2'] = avg2
    return df

In [196]:
instId = "PEPE-USDT-SWAP"
df = get_df(instId, "1H")
df

100%|██████████| 4/4 [00:01<00:00,  3.46it/s]

,ts,open,high,low,close,volume,volCcy,volCcyQuote,_,hlc3,mfi,rsi,stoch,sigStoch,resMfi,signal,avg,avg2
0,2024-05-27 05:00:00,0.000016078,0.000016189,0.000015902,0.000016109,121198.3,1211983000000,19439542.325,1,0.00001606666666666666666666666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-27 06:00:00,0.000016108,0.000016119,0.00001585,0.000015962,101371.1,1013711000000,16203031.287,1,0.000015977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-05-27 07:00:00,0.000015961,0.000016038,0.00001583,0.000016019,161552.6,1615526000000,25751207.072,1,0.00001596233333333333333333333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-05-27 08:00:00,0.000016019,0.000016828,0.000015989,0.000016454,575551.1,5755511000000,94800257.428,1,0.00001642366666666666666666666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-05-27 09:00:00,0.000016455,0.00001655,0.00001633,0.000016456,201449.7,2014497000000,33125887.488,1,0.00001644533333333333333333333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2024-06-10 04:00:00,0.000012799,0.000012814,0.00001264,0.000012695,88783.4,887834000000,11284443.799,1,0.00001271633333333333333333333333,82.178179,58.096186,86.633281,96.201244,13.794286,69.789317,51.401638,50.894691
336,2024-06-10 05:00:00,0.000012693,0.000012792,0.000012649,0.000012773,63756,637560000000,8114200.377,1,0.000012738,79.172367,58.907668,75.009345,91.203113,15.381514,66.989085,46.840534,48.372458
337,2024-06-10 06:00:00,0.000012773,0.000012895,0.00001272,0.000012799,80665.9,806659000000,10334300.774,1,0.00001280466666666666666666666667,76.708844,61.385528,82.073712,88.180562,18.115042,69.388083,48.376702,48.679436
338,2024-06-10 07:00:00,0.000012799,0.000012815,0.000012712,0.000012756,51885,518850000000,6624213.219,1,0.000012761,66.550169,58.881048,82.016542,85.146576,17.995239,65.726518,44.159199,46.046629
339,2024-06-10 08:00:00,0.000012757,0.000012772,0.000012578,0.000012606,65134.7,651347000000,8236861.129,0,0.000012652,69.690295,53.061465,59.917547,77.130085,16.023325,58.280335,32.396043,38.449269

In [197]:
rsiLen = 14
smoothLen = 2

# -----------------

inputMfiLen = 30
smoothHist = 2
fastMfiLen = round(inputMfiLen / 1.33)
slowMfiLen = round(inputMfiLen * 1.33)

# ---------------

MFI_LEN     = 7
STOCH_K     = 2
STOCH_D     = 5
SMOOTH_LEN  = 1.75
STOCH_WEIGHT = 0.4
OVERBOUGHT   = 60.0
EXTEND_MULT  = 1
mfiWeight    = 0.4


rsiLen = 14

UP_BORDER = 50
DN_BORDER = -50
lastSigBar = 0

MAX_ARR_PIV_SIZE = 5
MAX_ARR_LINE_SIZE = 250
PIV_LEN_LEFT = 7 
PIV_LEN_RIGHT = 1 
MIN_PEAK_DIST = 7
MAX_PEAK_DIST = 80

In [198]:

piv_high = deque()
piv_low = deque()
# 初始化双端队列
all_ind_val = deque(maxlen=100)
all_lows = deque(maxlen=100)
all_highs = deque(maxlen=100)

# 模拟每个柱子被确认后的操作
for index, row in df.iterrows():
    # 将当前柱子的指标值、最低价和最高价插入到双端队列的左端
    all_ind_val.appendleft(row['avg'])
    all_lows.appendleft(row['low'])
    all_highs.appendleft(row['high'])

# 定义 Point 类
class Point:
    def __init__(self, price, ndx):
        self.price = price
        self.ndx = ndx
        

class Pivot:
    def __init__(self, price, ndx, indicator):
        self.price = price
        self.ndx = ndx
        self.indicator = indicator
        
        
class ValueChecker:
    
    def __init__(self, bar_index):
        self.bar_index = bar_index

    def is_greater_ind_value(self, start, end, max_ind_val):
        res = True
        for i in range(self.bar_index - end, self.bar_index - start + 1):
            if all_ind_val[i] > max_ind_val:
                res = False
                break
        return res

    def is_lower_ind_value(self, start, end, min_ind_val):
        res = True
        for i in range(self.bar_index - start, self.bar_index - end + 1):
            if all_ind_val[i] < min_ind_val:
                res = False
                break
        return res

    def is_greater_high(self, start, end, point_high):
        res = True
        for i in range(self.bar_index - end, self.bar_index - start + 1):
            if all_highs[i] > point_high:
                res = False
                break
        return res

    def is_lower_low(self, start, end, point_low):
        res = True
        for i in range(self.bar_index - start, self.bar_index - end + 1):
            if all_lows[i] < point_low:
                res = False
                break
        return res


# 定义添加 Pivot High 的函数
def add_pivot_high(new_piv):
    if len(piv_high) > 0:
        prev = piv_high[0]
        if prev.price < new_piv.price and prev.indicator < new_piv.indicator:
            piv_high.popleft()
    piv_high.appendleft(new_piv)
    if len(piv_high) > MAX_ARR_PIV_SIZE:
        piv_high.pop()

# 定义添加 Pivot Low 的函数
def add_pivot_low(new_piv):
    if len(piv_low) > 0:
        prev = piv_low[0]
        if prev.price > new_piv.price and prev.indicator > new_piv.indicator:
            piv_low.popleft()
    piv_low.appendleft(new_piv)
    if len(piv_low) > MAX_ARR_PIV_SIZE:
        piv_low.pop()
    
def transform(src, mult=1):
    tmp = (src / 100 - 0.5) * 2
    sign = np.where(tmp > 0, 1, -1)
    return mult * 100 * sign * np.power(np.abs(tmp), 0.75)


def search_bear_div(newpiv: Pivot, checker: ValueChecker):
    result = False
    last_ind_high = newpiv.indicator
    if last_ind_high <= 0:
        return False
    for piv in piv_high:
        if newpiv.ndx - piv.ndx >= MAX_PEAK_DIST:
            break
        if piv.price > newpiv.price:
            break
        if piv.indicator > last_ind_high:
            last_ind_high = piv.indicator
        if piv.price <= newpiv.price and piv.indicator > newpiv.indicator and piv.indicator >= last_ind_high and (newpiv.ndx - piv.ndx >= MIN_PEAK_DIST) and piv.indicator > 50:
            if checker.is_greater_ind_value(piv.ndx, newpiv.ndx, piv.indicator) and checker.is_greater_high(piv.ndx, newpiv.ndx, newpiv.price):
                result = True
                break
    return result
    

def search_bull_div(new_piv, checker: ValueChecker):
    result = False
    new_ind_low = new_piv.indicator
    if new_ind_low >= 0:
        return result
    for piv in piv_low:
        if new_piv.ndx - piv.ndx >= MAX_PEAK_DIST:
            break
        if piv.price < new_piv.price:
            break
        if piv.indicator < new_ind_low:
            new_ind_low = piv.indicator
        if (piv.price >= new_piv.price and piv.indicator < new_piv.indicator and 
            piv.indicator <= new_ind_low and 
            (new_piv.ndx - piv.ndx >= MIN_PEAK_DIST) and piv.indicator < -50):
            if (checker.is_lower_ind_value(piv.ndx, new_piv.ndx, piv.indicator, all_ind_val) and 
                checker.is_lower_low(piv.ndx, new_piv.ndx, new_piv.price, all_lows)):
                result = True
                break
    return result

def pivot_high(series, left_bars, right_bars):
    """检查给定点是否是一个 pivot high，即它比左边和右边的 left_bars 和 right_bars 数量的点都高。"""
    pivots = [np.nan] * len(series)
    for i in range(left_bars, len(series) - right_bars):
        is_pivot = True
        for j in range(1, left_bars + 1):
            if series[i] <= series[i - j]:
                is_pivot = False
                break
        for j in range(1, right_bars + 1):
            if series[i] <= series[i + j]:
                is_pivot = False
                break
        if is_pivot:
            pivots[i+right_bars] = series[i]
    return pivots

def pivot_low(series, left_bars, right_bars):
    """检查给定点是否是一个 pivot low，即它比左边和右边的 left_bars 和 right_bars 数量的点都低。"""
    pivots = [np.nan] * len(series)
    for i in range(left_bars, len(series) - right_bars):
        is_pivot = True
        for j in range(1, left_bars + 1):
            if series[i] >= series[i - j]:
                is_pivot = False
                break
        for j in range(1, right_bars + 1):
            if series[i] >= series[i + j]:
                is_pivot = False
                break
        if is_pivot:
            pivots[i+right_bars] = series[i]
    return pivots

def divergence_calcs(df):
    df = df.copy()
    df["ph"] = pivot_high(df["high"], PIV_LEN_LEFT, PIV_LEN_RIGHT)
    df["pl"] = pivot_low(df["low"], PIV_LEN_LEFT, PIV_LEN_RIGHT)
    df["phI"] = pivot_high(df["avg"], PIV_LEN_LEFT, PIV_LEN_RIGHT)
    df["plI"] = pivot_low(df["avg"], PIV_LEN_LEFT, PIV_LEN_RIGHT)
    
    df["lastPhPrice"] = np.nan
    df["lastPlPrice"] = np.nan
    df["lastPhNdx"] = np.nan
    df["lastPlNdx"] = np.nan
    df["BullDiv"] = False
    df["BearDiv"] = False

    for i in range(len(df)):
        row = df.iloc[i]
        # 看跌背离
        phI = df['phI'][i]
        if pd.isnull(phI) or pd.isnull(df['ph'][i]):
            continue
        lastPh = Point(df['ph'][i], i - PIV_LEN_RIGHT)    
        sig = phI
        sigNdx = i - PIV_LEN_RIGHT
        if sigNdx - lastPh.ndx <= 2:
            # print(row["ts"], lastPh.price, sig)
            pivot = Pivot(lastPh.price, sigNdx, sig)
            result = search_bear_div(pivot, ValueChecker(i))
            df.at[i, 'BearDiv'] = result
            add_pivot_high(pivot)
            
        # 看涨背离
        plI = df['plI'][i]
        if pd.isnull(phI) or pd.isnull(df['pl'][i]):
            continue
        lastPl = Point(df['pl'][i], i - PIV_LEN_RIGHT)
        sig = plI
        sigNdx = i - PIV_LEN_RIGHT
        if sigNdx - lastPl.ndx <= 2:
            pivot = Pivot(lastPl.price, sigNdx, sig)
            result = search_bull_div(pivot, ValueChecker(i))
            if result:
                print(row["ts"], lastPl.price, sig)
            df.at[i, 'BullDiv'] = result
            add_pivot_low(pivot)
    return df

In [199]:
df = divergence_calcs(df)
df[df["ts"] == "2024-06-08 03:00:00"][["ph", "pl"]]
df[df["ts"] == "2024-06-07 21:00:00"][["ph", "pl"]]

      ph           pl
286  NaN  0.000011013

      ph           pl
280  NaN  0.000013461

In [200]:
df[df["BearDiv"] | df["BullDiv"]][["ts", "BearDiv", "BullDiv"]]

Empty DataFrame
Columns: [ts, BearDiv, BullDiv]
Index: []